### ISSUE TITLE
Gamestat/Tcp games  key 

### ISSUE THREAD

**Issue by Agentwii** [sepalani/GamestatsHTTP#46]
Gamestats / tcp games wii and wiiware I give a hand for the player who plays on wiimmfi is games that needs Gamestats and tcp part1
http://www.mediafire.com/file/ipl1fnn05h0ml6t/Gamestats%2CTCP+PACK1.txt

**Comment by sepalani** [comment]
First of, this issue looks invalid to me. Gamestats TCP (Gamespy's Gamestats server) has nothing to do with Gamestats HTTP (Nintendo's Gamestats2 server). Then, I pretty sure you screwed up your regexp pretty badly as it doesn't make sense and because mine had a quantifier and it doesn't look like so on yours.

Feel free to reopen if and only if I'm wrong.
